# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Rubric
version:      0.00_10
version_from: lib/Rubric/WebApp.pm
installdirs:  site
requires:
    CGI::Application:              3
    Class::DBI:                    0.96
    Class::DBI::AbstractSearch:    0
    Config::Auto:                  0.11
    DBD::SQLite:                   1.07
    Digest::MD5:                   0
    Template:                      2
    Template::Plugin::Class:       0.12
    Time::Piece:                   0
    YAML:                          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
