author: Ricardo SIGNES <rjbs@cpan.org>
distribution_type: module
generated_by: Module::Install version 0.62
license: perl
name: Rubric
no_index: 
  directory: 
    - inc
    - t
requires: 
  CGI::Application: 3
  CGI::Application::Plugin::Session: 0
  CGI::Carp: 0
  Class::DBI: 0.96
  Class::DBI::AbstractSearch: 0
  Config::Auto: 0.11
  DBD::SQLite: 1.08
  Date::Span: 1.12
  Digest::MD5: 0
  Email::Address: 0
  Email::Send: 0
  Encode: 2
  Getopt::Long::Descriptive: 0.03
  HTML::Widget::Factory: 0.03
  HTTP::Server::Simple: 0.09
  Template: 2
  Template::Plugin::Class: 0.12
  Test::HTTP::Server::Simple: 0.02
  Test::WWW::Mechanize: 1.04
  Time::Local: 0
  Time::Piece: 0
  YAML: 0
tests: " t/00-load.t t/10-dbsetup.t t/20-testdata.t t/config_custom.t t/config_default.t t/entry.t t/entry_format.t t/entry_query.t t/link.t t/pod-coverage.t t/pod.t t/privacy.t t/renderer.t t/tagstrings.t t/uri.t t/user.t t/www/www_main.t"
version: 0.140
