# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Rubric
version:      0.00_01
version_from: lib/Rubric/WebApp.pm
installdirs:  site
requires:
    Class::DBI:                    0.96
    Class::DBI::AbstractSearch:    0
    Config::Auto:                  0.11
    DBD::SQLite:                   1.07
    Template:                      2

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
