---
author:
  - 'Ricardo SIGNES <rjbs@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Rubric
name: Rubric
no_index:
  directory:
    - inc
    - share
    - t
    - xt
requires:
  App::Cmd: 0
  CGI::Application: 3
  CGI::Application::PSGI: 0
  CGI::Carp: 0
  Class::DBI: 0.96
  Class::DBI::AbstractSearch: 0
  Class::DBI::utf8: 0.2
  Crypt::CBC: 0
  Crypt::Rijndael: 0
  DBD::SQLite: 1.08
  Date::Span: 1.12
  DateTime: 0
  Digest::MD5: 0
  Email::Address: 0
  Email::Send: 0
  Encode: 2
  File::ShareDir: 0
  Getopt::Long::Descriptive: 0.03
  HTML::CalendarMonth: 0
  HTML::TagCloud: 0
  HTML::Widget::Factory: 0.03
  HTTP::Server::Simple: 0.09
  JSON: 2
  MIME::Base64: 0
  Plack::Builder: 0
  String::TagString: 0
  String::Truncate: 0
  Sub::Exporter: 0
  Template: 2
  Template::Plugin::Class: 0.12
  Test::HTTP::Server::Simple: 0.02
  Test::WWW::Mechanize: 1.04
  Time::Local: 0
  Time::Piece: 0
  YAML: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.149
