---
abstract: 'a notes and bookmarks manager with tagging'
author:
  - 'Ricardo SIGNES <rjbs@cpan.org>'
build_requires:
  DBD::SQLite: 1.08
  Exporter: 0
  File::Copy: 0
  File::Path: 0
  HTTP::Server::Simple: 0.08
  HTTP::Server::Simple::CGI: 0
  Test::File::ShareDir: 0
  Test::HTTP::Server::Simple: 0.02
  Test::More: 0.96
  Test::WWW::Mechanize: 1.04
  lib: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  File::ShareDir::Install: 0.03
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Rubric
requires:
  App::Cmd: 0
  App::Cmd::Command: 0
  App::Cmd::Command::commands: 0
  CGI::Application: 3
  CGI::Carp: 0
  CGI::Cookie: 0
  Carp: 0
  Class::Accessor: 0
  Class::DBI: 0.96
  Class::DBI::AbstractSearch: 0
  Class::DBI::utf8: 0
  Crypt::CBC: 0
  Crypt::Rijndael: 0
  DBI: 0
  Date::Span: 1.12
  DateTime: 0
  Digest::MD5: 0
  Email::Address: 0
  Email::Sender::Simple: 0
  Encode: 2
  File::ShareDir: 0
  File::Spec: 0
  HTML::CalendarMonth: 0
  HTML::TagCloud: 0
  HTML::Widget::Factory: 0.03
  JSON: 2
  LWP::Simple: 0
  MIME::Base64: 0
  Scalar::Util: 0
  String::TagString: 0
  String::Truncate: 0
  Sub::Exporter: 0
  Template: 2.00
  Template::Filters: 0
  Template::Plugin::Class: 0.12
  Time::Piece: 0
  YAML::XS: 0
  base: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/rjbs/Rubric/issues
  homepage: https://github.com/rjbs/Rubric
  repository: https://github.com/rjbs/Rubric.git
version: 0.154
x_Dist_Zilla:
  perl:
    version: 5.019004
  plugins:
    -
      class: Dist::Zilla::Plugin::Git::GatherDir
      name: '@Filter/Git::GatherDir'
      version: 2.014
    -
      class: Dist::Zilla::Plugin::CheckPrereqsIndexed
      name: '@Filter/CheckPrereqsIndexed'
      version: 0.009
    -
      class: Dist::Zilla::Plugin::CheckExtraTests
      name: '@Filter/CheckExtraTests'
      version: 0.011
    -
      class: Dist::Zilla::Plugin::PromptIfStale
      name: '@Filter/RJBS-Outdated'
      version: 0.008
    -
      class: Dist::Zilla::Plugin::PromptIfStale
      name: '@Filter/CPAN-Outdated'
      version: 0.008
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Filter/@Filter/PruneCruft'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Filter/@Filter/ManifestSkip'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Filter/@Filter/MetaYAML'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::License
      name: '@Filter/@Filter/License'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@Filter/@Filter/Readme'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Filter/@Filter/ExecDir'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Filter/@Filter/ShareDir'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@Filter/@Filter/MakeMaker'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Filter/@Filter/Manifest'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Filter/@Filter/TestRelease'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Filter/@Filter/ConfirmRelease'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Filter/@Filter/UploadToCPAN'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@Filter/AutoPrereqs'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: '@Filter/Git::NextVersion'
      version: 2.014
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@Filter/PkgVersion'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Filter/MetaConfig'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Filter/MetaJSON'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@Filter/NextRelease'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::Test::ChangesHasContent
      name: '@Filter/Test::ChangesHasContent'
      version: 0.006
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Filter/PodSyntaxTests'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::ReportVersions::Tiny
      name: '@Filter/ReportVersions::Tiny'
      version: 1.10
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: test
          type: requires
      name: '@Filter/TestMoreWithSubtests'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::PodWeaver
      config:
        Dist::Zilla::Plugin::PodWeaver:
          config_plugin: '@RJBS'
          finder:
            - ':InstallModules'
            - ':ExecFiles'
      name: '@Filter/PodWeaver'
      version: 3.102000
    -
      class: Dist::Zilla::Plugin::GithubMeta
      name: '@Filter/GithubMeta'
      version: 0.42
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@Filter/@Git/Check'
      version: 2.014
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@Filter/@Git/Commit'
      version: 2.014
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Filter/@Git/Tag'
      version: 2.014
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@Filter/@Git/Push'
      version: 2.014
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: Prereqs
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: test
          type: requires
      name: TestRequires
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.300039
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.300039
