name: Rubric
version: 0.13_01
author: Ricardo SIGNES <rjbs@cpan.org>
license: perl
distribution_type: module
tests:  t/config_custom.t t/pod.t t/renderer.t t/entry.t t/20_testdata.t t/link.t t/10_dbsetup.t t/user.t t/config_default.t t/pod-coverage.t t/00_load.t t/entry_query.t t/www/www_main.t
requires:
  CGI::Application: 3
  CGI::Carp: 0
  Class::DBI: 0.96
  Config::Auto: 0.11
  Date::Span: 1.12
  DBD::SQLite: 1.08
  Digest::MD5: 0
  Email::Address: 0
  Email::Send: 0
  Encode: 2
  Template: 2
  Time::Local: 0
  Time::Piece: 0
  YAML: 0
  Class::DBI::AbstractSearch: 0
  HTML::Widget::Factory: 0.01
  HTTP::Server::Simple: 0.09
  Getopt::Long::Descriptive: 0.02
  Template::Plugin::Class: 0.12
  Test::WWW::Mechanize: 1.04
  CGI::Application::Plugin::Session: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.39
